language: java
jdk:
  - oraclejdk8
before_install:
  - wget -P $TRAVIS_BUILD_DIR/ https://github.com/LosPecesDelInfierno/jrpg-2017a-servidor/blob/master/jrpg-dominio-0.1.jar
  - wget -P $TRAVIS_BUILD_DIR/ https://github.com/LosPecesDelInfierno/jrpg-2017a-servidor/blob/master/jrpg-cliente-0.1.jar